name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: gradle build --stacktrace
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Gradle Unit Test
        run: gradle test

  checkstyle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Run Checkstyle on Main
        run: gradle checkstyleMain
      - name: Upload checkstyle Main artifact
        uses: actions/upload-artifact@v3
        with:
          name: mainstyle-log-file
          path: main-output.log
      - name: Run Checkstyle on Test
        run: gradle checkstyleTest
      - name: Upload checkstyle Test artifact
        uses: actions/upload-artifact@v3
        with:
          name: teststyle-log-file
          path: test-output.log


