name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: First interaction
        uses: actions/first-interaction@v1.1.0
        with:
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    # Comment to post on an individual's first issue
          issue-message: '# Message with markdown.\nThis is the message that will be displayed on users first issue.'
    # Comment to post on an individual's first pull request
          pr-message: 'Message that will be displayed on users first pr. Look, a `code block` for markdown.'
